// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0
// source: api/generateshorturl/generateshorturl.proto

package generateshorturl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateShortUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GenerateShortUrlRequest) Reset() {
	*x = GenerateShortUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_generateshorturl_generateshorturl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateShortUrlRequest) ProtoMessage() {}

func (x *GenerateShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_generateshorturl_generateshorturl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateShortUrlRequest.ProtoReflect.Descriptor instead.
func (*GenerateShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_generateshorturl_generateshorturl_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateShortUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GenerateShortUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorturl   string `protobuf:"bytes,1,opt,name=shorturl,proto3" json:"shorturl,omitempty"`
	StatusCode int32  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
}

func (x *GenerateShortUrlResponse) Reset() {
	*x = GenerateShortUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_generateshorturl_generateshorturl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateShortUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateShortUrlResponse) ProtoMessage() {}

func (x *GenerateShortUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_generateshorturl_generateshorturl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateShortUrlResponse.ProtoReflect.Descriptor instead.
func (*GenerateShortUrlResponse) Descriptor() ([]byte, []int) {
	return file_api_generateshorturl_generateshorturl_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateShortUrlResponse) GetShorturl() string {
	if x != nil {
		return x.Shorturl
	}
	return ""
}

func (x *GenerateShortUrlResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_api_generateshorturl_generateshorturl_proto protoreflect.FileDescriptor

var file_api_generateshorturl_generateshorturl_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x22,
	0x2b, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x56, 0x0a, 0x18,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x32, 0x7f, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x6b, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x29, 0x2e, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_generateshorturl_generateshorturl_proto_rawDescOnce sync.Once
	file_api_generateshorturl_generateshorturl_proto_rawDescData = file_api_generateshorturl_generateshorturl_proto_rawDesc
)

func file_api_generateshorturl_generateshorturl_proto_rawDescGZIP() []byte {
	file_api_generateshorturl_generateshorturl_proto_rawDescOnce.Do(func() {
		file_api_generateshorturl_generateshorturl_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_generateshorturl_generateshorturl_proto_rawDescData)
	})
	return file_api_generateshorturl_generateshorturl_proto_rawDescData
}

var file_api_generateshorturl_generateshorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_generateshorturl_generateshorturl_proto_goTypes = []interface{}{
	(*GenerateShortUrlRequest)(nil),  // 0: generateshorturl.GenerateShortUrlRequest
	(*GenerateShortUrlResponse)(nil), // 1: generateshorturl.GenerateShortUrlResponse
}
var file_api_generateshorturl_generateshorturl_proto_depIdxs = []int32{
	0, // 0: generateshorturl.GenerateShortUrl.GenerateShortUrl:input_type -> generateshorturl.GenerateShortUrlRequest
	1, // 1: generateshorturl.GenerateShortUrl.GenerateShortUrl:output_type -> generateshorturl.GenerateShortUrlResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_generateshorturl_generateshorturl_proto_init() }
func file_api_generateshorturl_generateshorturl_proto_init() {
	if File_api_generateshorturl_generateshorturl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_generateshorturl_generateshorturl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateShortUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_generateshorturl_generateshorturl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateShortUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_generateshorturl_generateshorturl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_generateshorturl_generateshorturl_proto_goTypes,
		DependencyIndexes: file_api_generateshorturl_generateshorturl_proto_depIdxs,
		MessageInfos:      file_api_generateshorturl_generateshorturl_proto_msgTypes,
	}.Build()
	File_api_generateshorturl_generateshorturl_proto = out.File
	file_api_generateshorturl_generateshorturl_proto_rawDesc = nil
	file_api_generateshorturl_generateshorturl_proto_goTypes = nil
	file_api_generateshorturl_generateshorturl_proto_depIdxs = nil
}
