// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: api/getshorturl/getshorturl.proto

package getshorturl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetShortUrlClient is the client API for GetShortUrl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetShortUrlClient interface {
	GetShortUrl(ctx context.Context, in *GetShortUrlRequest, opts ...grpc.CallOption) (*GetShortUrlResponse, error)
}

type getShortUrlClient struct {
	cc grpc.ClientConnInterface
}

func NewGetShortUrlClient(cc grpc.ClientConnInterface) GetShortUrlClient {
	return &getShortUrlClient{cc}
}

func (c *getShortUrlClient) GetShortUrl(ctx context.Context, in *GetShortUrlRequest, opts ...grpc.CallOption) (*GetShortUrlResponse, error) {
	out := new(GetShortUrlResponse)
	err := c.cc.Invoke(ctx, "/getshorturl.GetShortUrl/GetShortUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetShortUrlServer is the server API for GetShortUrl service.
// All implementations must embed UnimplementedGetShortUrlServer
// for forward compatibility
type GetShortUrlServer interface {
	GetShortUrl(context.Context, *GetShortUrlRequest) (*GetShortUrlResponse, error)
	mustEmbedUnimplementedGetShortUrlServer()
}

// UnimplementedGetShortUrlServer must be embedded to have forward compatible implementations.
type UnimplementedGetShortUrlServer struct {
}

func (UnimplementedGetShortUrlServer) GetShortUrl(context.Context, *GetShortUrlRequest) (*GetShortUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShortUrl not implemented")
}
func (UnimplementedGetShortUrlServer) mustEmbedUnimplementedGetShortUrlServer() {}

// UnsafeGetShortUrlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetShortUrlServer will
// result in compilation errors.
type UnsafeGetShortUrlServer interface {
	mustEmbedUnimplementedGetShortUrlServer()
}

func RegisterGetShortUrlServer(s grpc.ServiceRegistrar, srv GetShortUrlServer) {
	s.RegisterService(&GetShortUrl_ServiceDesc, srv)
}

func _GetShortUrl_GetShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShortUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetShortUrlServer).GetShortUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/getshorturl.GetShortUrl/GetShortUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetShortUrlServer).GetShortUrl(ctx, req.(*GetShortUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetShortUrl_ServiceDesc is the grpc.ServiceDesc for GetShortUrl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetShortUrl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "getshorturl.GetShortUrl",
	HandlerType: (*GetShortUrlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShortUrl",
			Handler:    _GetShortUrl_GetShortUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/getshorturl/getshorturl.proto",
}
